package agent

import (
	"context"

	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/websearch"
)

// BaseAgent defines the basic interface for all agents in the RAG system.
// This interface provides the basic invocation method that all agents must implement.
type BaseAgent interface {
	// Invoke executes the agent with the given query and returns the result.
	//
	// ctx: Context for cancellation and timeout
	// query: The query string to process
	// kwargs: Additional keyword arguments (optional parameters)
	//
	// Returns: The result of invoking the agent (type depends on implementation)
	Invoke(ctx context.Context, query string, kwargs map[string]interface{}) (interface{}, error)
}

// RAGAgent extends BaseAgent with methods specific to Retrieval-Augmented Generation.
// This interface defines the standard methods for RAG agents: retrieval and query.
type RAGAgent interface {
	BaseAgent

	// Retrieve retrieves relevant documents from the knowledge base based on the query.
	//
	// ctx: Context for cancellation and timeout
	// query: The query string to retrieve documents for
	// kwargs: Additional keyword arguments, which may include:
	//   - max_iter: Maximum number of iterations for refinement (optional)
	//
	// Returns:
	//   - []RetrievalResult: List of retrieved document results
	//   - int: Total number of tokens used by the LLM
	//   - map[string]interface{}: Additional metadata (e.g., intermediate_context)
	//   - error: Error if retrieval fails
	Retrieve(ctx context.Context, query string, kwargs map[string]interface{}) ([]RetrievalResult, int, map[string]interface{}, error)

	// Query executes a query and returns the final answer along with retrieved results.
	//
	// ctx: Context for cancellation and timeout
	// query: The query string to answer
	// kwargs: Additional keyword arguments, which may include:
	//   - max_iter: Maximum number of iterations for refinement (optional)
	//
	// Returns:
	//   - string: The final answer generated by the LLM
	//   - []RetrievalResult: List of all retrieved document results
	//   - int: Total number of tokens used by the LLM (including final answer generation)
	//   - error: Error if query fails
	Query(ctx context.Context, query string, kwargs map[string]interface{}) (string, []RetrievalResult, int, error)
}

// AgentDescription provides a way to attach descriptions to agent implementations.
// This is similar to Python's @describe_class decorator.
type AgentDescription struct {
	Description string
}

// DescribeAgent creates an AgentDescription with the given description text.
//
// Example usage:
func DescribeAgent(description string) AgentDescription {
	return AgentDescription{
		Description: description,
	}
}

// DefaultInternetSearchConfig returns default internet search configuration
func DefaultInternetSearchConfig() *InternetSearchConfig {
	return &InternetSearchConfig{
		Enabled:    false,
		MaxResults: 5,
		Provider:   nil,
	}
}

// InternetSearchConfig holds configuration for internet search
type InternetSearchConfig struct {
	Enabled    bool // Whether internet search is enabled
	MaxResults int  // Maximum number of results to return per query
	Provider   websearch.InternetSearchProvider
}

// DefaultRAGConfig holds configuration for DefaultRAG agent
type DefaultRAGConfig struct {
	TopK         int
	Threshold    float64
	Rerank       bool
	RerankTopK   int
	HybridSearch bool
}

// DefaultRAGConfigWithDefaults returns a DefaultRAGConfig with default values
func DefaultRAGConfigWithDefaults() *DefaultRAGConfig {
	return &DefaultRAGConfig{
		TopK:         10,
		Threshold:    0.0,
		Rerank:       false,
		RerankTopK:   20,
		HybridSearch: false,
	}
}
