package agent

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/embedding"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/llm"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/schema"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/vectordb"
)

const (
	// Prompt templates
	followupQueryPrompt = `You are using a search tool to answer the main query by iteratively searching the database. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search tool may not understand complex questions.

## Previous intermediate queries and answers
%s

## Main query to answer
%s

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else.`

	intermediateAnswerPrompt = `Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond "No relevant information found" if the documents do not contain useful information.

## Documents
%s

## Query
%s

Respond with a concise answer only, do not explain yourself or output anything else.`

	finalAnswerPrompt = `Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.

## Documents
%s

## Intermediate queries and answers
%s

## Main query
%s

Respond with an appropriate answer only, do not explain yourself or output anything else.`

	reflectionPrompt = `Given the following intermediate queries and answers, judge whether you have enough information to answer the main query. If you believe you have enough information, respond with "Yes", otherwise respond with "No".

## Intermediate queries and answers
%s

## Main query
%s

Respond with "Yes" or "No" only, do not explain yourself or output anything else.`

	getSupportedDocsPrompt = `Given the following documents, select the ones that are support the Q-A pair.

## Documents
%s

## Q-A Pair
### Question
%s
### Answer
%s

Respond with a python list of indices of the selected documents.`
)

// RetrievalResult represents a result retrieved from the vector database
type RetrievalResult struct {
	Text     string
	Score    float64
	Document schema.Document
	Metadata map[string]interface{}
}

// ChatResponse represents a response from a chat model
type ChatResponse struct {
	Content     string
	TotalTokens int
}

// ChatLLM extends the LLM provider interface with chat capabilities
type ChatLLM interface {
	llm.Provider
	Chat(ctx context.Context, messages []ChatMessage) (*ChatResponse, error)
	RemoveThink(content string) string
	LiteralEval(content string) ([]int, error)
}

// ChatMessage represents a message in a chat conversation
type ChatMessage struct {
	Role    string
	Content string
}

// ChainOfRAG implements Chain of Retrieval-Augmented Generation agent
// This agent can decompose complex queries and gradually find the fact information of sub-queries.
// It is very suitable for handling concrete factual queries and multi-hop questions.
// ChainOfRAG implements the RAGAgent interface.
type ChainOfRAG struct {
	llm             ChatLLM
	embeddingModel  embedding.Provider
	vectorDB        vectordb.VectorStoreProvider
	maxIter         int
	earlyStopping   bool
	textWindowSplit bool
}

// Ensure ChainOfRAG implements RAGAgent interface at compile time
var _ RAGAgent = (*ChainOfRAG)(nil)

// NewChainOfRAG creates a new ChainOfRAG agent
func NewChainOfRAG(
	llm ChatLLM,
	embeddingModel embedding.Provider,
	vectorDB vectordb.VectorStoreProvider,
	maxIter int,
	earlyStopping bool,
	textWindowSplit bool,
) (*ChainOfRAG, error) {
	return &ChainOfRAG{
		llm:             llm,
		embeddingModel:  embeddingModel,
		vectorDB:        vectorDB,
		maxIter:         maxIter,
		earlyStopping:   earlyStopping,
		textWindowSplit: textWindowSplit,
	}, nil
}

// reflectGetSubquery generates a follow-up query based on intermediate context
func (c *ChainOfRAG) reflectGetSubquery(ctx context.Context, query string, intermediateContext []string) (string, int, error) {
	contextStr := strings.Join(intermediateContext, "\n")
	prompt := fmt.Sprintf(followupQueryPrompt, contextStr, query)

	response, err := c.llm.Chat(ctx, []ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return "", 0, err
	}

	return c.llm.RemoveThink(response.Content), response.TotalTokens, nil
}

// retrieveAndAnswer retrieves documents and generates an intermediate answer
func (c *ChainOfRAG) retrieveAndAnswer(ctx context.Context, query string) (string, []RetrievalResult, int, error) {
	queryVector, err := c.embeddingModel.GetEmbedding(ctx, query)
	if err != nil {
		return "", nil, 0, fmt.Errorf("failed to get embedding: %w", err)
	}

	searchOptions := &schema.SearchOptions{
		TopK:      20,
		Threshold: 0.0,
	}

	searchResults, err := c.vectorDB.SearchDocs(ctx, query, queryVector, searchOptions)
	if err != nil {
		return "", nil, 0, fmt.Errorf("search failed: %w", err)
	}

	allRetrievedResults := make([]RetrievalResult, 0)
	for _, result := range searchResults {
		allRetrievedResults = append(allRetrievedResults, RetrievalResult{
			Text:     result.Document.Content,
			Score:    result.Score,
			Document: result.Document,
			Metadata: result.Document.Metadata,
		})
	}

	allRetrievedResults = deduplicateResults(allRetrievedResults)

	formattedDocs := c.formatRetrievedResults(allRetrievedResults)
	prompt := fmt.Sprintf(intermediateAnswerPrompt, formattedDocs, query)

	response, err := c.llm.Chat(ctx, []ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return "", nil, 0, err
	}

	return c.llm.RemoveThink(response.Content), allRetrievedResults, response.TotalTokens, nil
}

// getSupportedDocs filters documents that support the Q-A pair
func (c *ChainOfRAG) getSupportedDocs(
	ctx context.Context,
	retrievedResults []RetrievalResult,
	query string,
	intermediateAnswer string,
) ([]RetrievalResult, int, error) {
	if strings.Contains(intermediateAnswer, "No relevant information found") {
		return []RetrievalResult{}, 0, nil
	}

	formattedDocs := c.formatRetrievedResults(retrievedResults)
	prompt := fmt.Sprintf(getSupportedDocsPrompt, formattedDocs, query, intermediateAnswer)

	response, err := c.llm.Chat(ctx, []ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return nil, 0, err
	}

	supportedIndices, err := c.llm.LiteralEval(response.Content)
	if err != nil {
		return nil, 0, err
	}

	supportedResults := make([]RetrievalResult, 0)
	for _, idx := range supportedIndices {
		if idx >= 0 && idx < len(retrievedResults) {
			supportedResults = append(supportedResults, retrievedResults[idx])
		}
	}

	return supportedResults, response.TotalTokens, nil
}

// checkHasEnoughInfo checks if there's enough information to answer the query
func (c *ChainOfRAG) checkHasEnoughInfo(ctx context.Context, query string, intermediateContexts []string) (bool, int, error) {
	if len(intermediateContexts) == 0 {
		return false, 0, nil
	}

	contextStr := strings.Join(intermediateContexts, "\n")
	prompt := fmt.Sprintf(reflectionPrompt, contextStr, query)

	response, err := c.llm.Chat(ctx, []ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return false, 0, err
	}

	content := strings.ToLower(strings.TrimSpace(c.llm.RemoveThink(response.Content)))
	hasEnoughInfo := content == "yes"
	return hasEnoughInfo, response.TotalTokens, nil
}

// Invoke executes the agent with the given query and returns the result.
// This implements the BaseAgent interface.
// For ChainOfRAG, Invoke calls Query and returns the answer string.
func (c *ChainOfRAG) Invoke(ctx context.Context, query string, kwargs map[string]interface{}) (interface{}, error) {
	answer, _, _, err := c.Query(ctx, query, kwargs)
	if err != nil {
		return nil, err
	}
	return answer, nil
}

// Retrieve retrieves relevant documents based on the input query and iteratively refines the search
// This implements the RAGAgent interface
func (c *ChainOfRAG) Retrieve(ctx context.Context, query string, kwargs map[string]interface{}) ([]RetrievalResult, int, map[string]interface{}, error) {
	iterations := c.maxIter
	if kwargs != nil {
		if maxIterVal, ok := kwargs["max_iter"].(int); ok {
			iterations = maxIterVal
		}
	}

	intermediateContexts := make([]string, 0)
	allRetrievedResults := make([]RetrievalResult, 0)
	tokenUsage := 0

	for iter := 0; iter < iterations; iter++ {
		followupQuery, nToken0, err := c.reflectGetSubquery(ctx, query, intermediateContexts)
		if err != nil {
			return nil, 0, nil, err
		}

		intermediateAnswer, retrievedResults, nToken1, err := c.retrieveAndAnswer(ctx, followupQuery)
		if err != nil {
			return nil, 0, nil, err
		}

		supportedRetrievedResults, nToken2, err := c.getSupportedDocs(ctx, retrievedResults, followupQuery, intermediateAnswer)
		if err != nil {
			return nil, 0, nil, err
		}

		allRetrievedResults = append(allRetrievedResults, supportedRetrievedResults...)
		intermediateIdx := len(intermediateContexts) + 1
		intermediateContexts = append(intermediateContexts,
			fmt.Sprintf("Intermediate query%d: %s\nIntermediate answer%d: %s", intermediateIdx, followupQuery, intermediateIdx, intermediateAnswer))
		tokenUsage += nToken0 + nToken1 + nToken2

		if c.earlyStopping {
			hasEnoughInfo, nTokenCheck, err := c.checkHasEnoughInfo(ctx, query, intermediateContexts)
			if err != nil {
				return nil, 0, nil, err
			}
			tokenUsage += nTokenCheck

			if hasEnoughInfo {
				break
			}
		}
	}

	allRetrievedResults = deduplicateResults(allRetrievedResults)
	additionalInfo := map[string]interface{}{
		"intermediate_context": intermediateContexts,
	}

	return allRetrievedResults, tokenUsage, additionalInfo, nil
}

// Query executes a query and returns the final answer along with all retrieved results
// This implements the RAGAgent interface
func (c *ChainOfRAG) Query(ctx context.Context, query string, kwargs map[string]interface{}) (string, []RetrievalResult, int, error) {
	allRetrievedResults, nTokenRetrieval, additionalInfo, err := c.Retrieve(ctx, query, kwargs)
	if err != nil {
		return "", nil, 0, err
	}

	intermediateContext, ok := additionalInfo["intermediate_context"].([]string)
	if !ok {
		intermediateContext = []string{}
	}

	formattedDocs := c.formatRetrievedResults(allRetrievedResults)
	contextStr := strings.Join(intermediateContext, "\n")
	prompt := fmt.Sprintf(finalAnswerPrompt, formattedDocs, contextStr, query)

	response, err := c.llm.Chat(ctx, []ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return "", nil, 0, err
	}

	finalAnswer := c.llm.RemoveThink(response.Content)
	return finalAnswer, allRetrievedResults, nTokenRetrieval + response.TotalTokens, nil
}

// formatRetrievedResults formats retrieved results for prompt
func (c *ChainOfRAG) formatRetrievedResults(retrievedResults []RetrievalResult) string {
	formattedDocuments := make([]string, 0)
	for i, result := range retrievedResults {
		text := result.Text
		if c.textWindowSplit {
			if widerText, ok := result.Metadata["wider_text"].(string); ok {
				text = widerText
			}
		}
		formattedDocuments = append(formattedDocuments, fmt.Sprintf("<Document %d>\n%s\n</Document %d>", i, text, i))
	}
	return strings.Join(formattedDocuments, "\n")
}

// deduplicateResults removes duplicate results based on text content
func deduplicateResults(results []RetrievalResult) []RetrievalResult {
	seen := make(map[string]bool)
	deduplicated := make([]RetrievalResult, 0)

	for _, result := range results {
		if !seen[result.Text] {
			seen[result.Text] = true
			deduplicated = append(deduplicated, result)
		}
	}

	return deduplicated
}

// RemoveThink removes content between <think> tags
func RemoveThink(content string) string {
	re := regexp.MustCompile(`(?s)<think>.*?</think>`)
	content = re.ReplaceAllString(content, "")
	return strings.TrimSpace(content)
}

// LiteralEval parses a string response into a list of integers
func LiteralEval(content string) ([]int, error) {
	content = strings.TrimSpace(content)
	content = RemoveThink(content)

	// Remove code blocks if present
	if strings.HasPrefix(content, "```") {
		lines := strings.Split(content, "\n")
		if len(lines) > 1 {
			content = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}

	// Try to find list pattern
	re := regexp.MustCompile(`\[[\d\s,]+\]`)
	matches := re.FindString(content)
	if matches == "" {
		// Try to find any list-like structure
		re2 := regexp.MustCompile(`\[.*?\]`)
		matches = re2.FindString(content)
	}

	if matches == "" {
		return nil, fmt.Errorf("no list found in content: %s", content)
	}

	// Parse the list
	matches = strings.Trim(matches, "[]")
	parts := strings.Split(matches, ",")
	result := make([]int, 0)

	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		val, err := strconv.Atoi(part)
		if err != nil {
			return nil, fmt.Errorf("invalid integer in list: %s", part)
		}
		result = append(result, val)
	}

	return result, nil
}
