package agent

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/embedding"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/llm"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/reranker"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/schema"
	"github.com/alibaba/higress/plugins/golang-filter/mcp-server/servers/rag/vectordb"
)

const (
	// Prompt templates
	followupQueryPrompt = `You are using a search tool to answer the main query by iteratively searching the database. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search tool may not understand complex questions.

## Previous intermediate queries and answers
%s

## Main query to answer
%s

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else.`

	intermediateAnswerPrompt = `Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond "No relevant information found" if the documents do not contain useful information.

## Documents
%s

## Query
%s

Respond with a concise answer only, do not explain yourself or output anything else.`

	finalAnswerPrompt = `Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.

## Documents
%s

## Intermediate queries and answers
%s

## Main query
%s

Please respond with an appropriate answer only. If the provided information is insufficient to answer the question, respond 'Insufficient Information'. Answer directly without explanation.
`

	reflectionPrompt = `Given the following intermediate queries and answers, judge whether you have enough information to answer the main query. If you believe you have enough information, respond with "Yes", otherwise respond with "No".

## Intermediate queries and answers
%s

## Main query
%s

Respond with "Yes" or "No" only, do not explain yourself or output anything else.`

	getSupportedDocsPrompt = `Given the following documents, select the ones that are support the Q-A pair.

## Documents
%s

## Q-A Pair
### Question
%s
### Answer
%s

Respond with a python list of indices of the selected documents.`
)

// RetrievalResult represents a result retrieved from the vector database
type RetrievalResult struct {
	Text     string
	Score    float64
	Document schema.Document
	Metadata map[string]interface{}
}

// ChainOfRAGDescription is the description for ChainOfRAG agent.
// This agent can decompose complex queries and gradually find the fact information of sub-queries.
// It is very suitable for handling concrete factual queries and multi-hop questions.
var ChainOfRAGDescription = DescribeAgent(
	"This agent can decompose complex queries and gradually find the fact information of sub-queries. " +
		"It is very suitable for handling concrete factual queries and multi-hop questions.",
)

// ChainOfRAG implements Chain of Retrieval-Augmented Generation agent
// This agent can decompose complex queries and gradually find the fact information of sub-queries.
// It is very suitable for handling concrete factual queries and multi-hop questions.
// ChainOfRAG implements the RAGAgent interface.
type ChainOfRAG struct {
	llm             llm.Provider
	embeddingModel  embedding.Provider
	vectorDB        vectordb.VectorStoreProvider
	rerankerClient  *reranker.RerankerClient
	config          *DefaultRAGConfig
	maxIter         int
	earlyStopping   bool
	textWindowSplit bool
}

// Description returns the description of ChainOfRAG agent
// This implements the DescribableAgent interface for use with RAGRouter
func (c *ChainOfRAG) Description() string {
	return ChainOfRAGDescription.Description
}

// Ensure ChainOfRAG implements RAGAgent interface at compile time
var _ RAGAgent = (*ChainOfRAG)(nil)

// NewChainOfRAG creates a new ChainOfRAG agent
func NewChainOfRAG(
	llm llm.Provider,
	embeddingModel embedding.Provider,
	vectorDB vectordb.VectorStoreProvider,
	rerankerClient *reranker.RerankerClient,
	config *DefaultRAGConfig,
	maxIter int,
	earlyStopping bool,
	textWindowSplit bool,
) (*ChainOfRAG, error) {

	if config == nil {
		config = DefaultRAGConfigWithDefaults()
	}
	return &ChainOfRAG{
		llm:             llm,
		embeddingModel:  embeddingModel,
		vectorDB:        vectorDB,
		rerankerClient:  rerankerClient,
		config:          config,
		maxIter:         maxIter,
		earlyStopping:   earlyStopping,
		textWindowSplit: textWindowSplit,
	}, nil
}

// reflectGetSubquery generates a follow-up query based on intermediate context
func (c *ChainOfRAG) reflectGetSubquery(ctx context.Context, query string, intermediateContext []string) (string, int, error) {
	fmt.Printf("[ChainOfRAG] Step 1: Generating follow-up query...\n")
	if len(intermediateContext) > 0 {
		fmt.Printf("[ChainOfRAG]   Previous intermediate contexts: %d\n", len(intermediateContext))
	}

	contextStr := strings.Join(intermediateContext, "\n")
	prompt := fmt.Sprintf(followupQueryPrompt, contextStr, query)

	response, err := c.llm.Chat(ctx, []llm.ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to generate follow-up query: %v\n", err)
		return "", 0, err
	}

	fmt.Printf("[ChainOfRAG]   Generated follow-up query: %s\n", response.Content)
	fmt.Printf("[ChainOfRAG]   Tokens used: %d\n", response.TotalTokens)
	return response.Content, response.TotalTokens, nil
}

// retrieveAndAnswer retrieves documents and generates an intermediate answer
func (c *ChainOfRAG) retrieveAndAnswer(ctx context.Context, query string, topK int, threshold float64) (string, []RetrievalResult, int, error) {
	fmt.Printf("[ChainOfRAG] Step 2: Retrieving documents and generating intermediate answer...\n")
	fmt.Printf("[ChainOfRAG]   Query: %s\n", query)
	fmt.Printf("[ChainOfRAG]   TopK: %d, Threshold: %.2f\n", topK, threshold)

	queryVector, err := c.embeddingModel.GetEmbedding(ctx, query)
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to get embedding: %v\n", err)
		return "", nil, 0, fmt.Errorf("failed to get embedding: %w", err)
	}

	searchOptions := &schema.SearchOptions{
		// TopK:      int(1.5 * float64(topK)), // Retrieve more documents to increase the chance of finding relevant documents
		TopK:      topK,
		Threshold: threshold,
	}

	var searchResults []schema.SearchResult
	if c.config.HybridSearch {
		searchResults, err = c.vectorDB.SearchHybridDocs(ctx, query, queryVector, searchOptions)
	} else {
		searchResults, err = c.vectorDB.SearchDocs(ctx, query, queryVector, searchOptions)
	}

	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Search failed: %v\n", err)
		return "", nil, 0, fmt.Errorf("search failed: %w", err)
	}

	fmt.Printf("[ChainOfRAG]   Retrieved %d documents from vector DB\n", len(searchResults))

	allRetrievedResults := make([]RetrievalResult, 0)
	for _, result := range searchResults {
		allRetrievedResults = append(allRetrievedResults, RetrievalResult{
			Text:     result.Document.Content,
			Score:    result.Score,
			Document: result.Document,
			Metadata: result.Document.Metadata,
		})
	}

	allRetrievedResults = deduplicateResults(allRetrievedResults)
	fmt.Printf("[ChainOfRAG]   After deduplication: %d documents\n", len(allRetrievedResults))

	formattedDocs := c.formatRetrievedResults(allRetrievedResults)
	prompt := fmt.Sprintf(intermediateAnswerPrompt, formattedDocs, query)

	response, err := c.llm.Chat(ctx, []llm.ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to generate intermediate answer: %v\n", err)
		return "", nil, 0, err
	}

	fmt.Printf("[ChainOfRAG]   Intermediate answer: %s\n", response.Content)
	fmt.Printf("[ChainOfRAG]   Tokens used: %d\n", response.TotalTokens)
	return response.Content, allRetrievedResults, response.TotalTokens, nil
}

// getSupportedDocs filters documents that support the Q-A pair
func (c *ChainOfRAG) getSupportedDocs(
	ctx context.Context,
	retrievedResults []RetrievalResult,
	query string,
	intermediateAnswer string,
) ([]RetrievalResult, int, error) {
	fmt.Printf("[ChainOfRAG] Step 3: Filtering supported documents...\n")
	fmt.Printf("[ChainOfRAG]   Input documents: %d\n", len(retrievedResults))

	if strings.Contains(intermediateAnswer, "No relevant information found") {
		fmt.Printf("[ChainOfRAG]   No relevant information found, skipping filtering\n")
		return []RetrievalResult{}, 0, nil
	}

	formattedDocs := c.formatRetrievedResults(retrievedResults)
	prompt := fmt.Sprintf(getSupportedDocsPrompt, formattedDocs, query, intermediateAnswer)

	response, err := c.llm.Chat(ctx, []llm.ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to filter documents: %v\n", err)
		return nil, 0, err
	}

	supportedIndices, err := LiteralEval(response.Content)
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to parse supported indices: %v\n", err)
		return nil, 0, err
	}

	fmt.Printf("[ChainOfRAG]   Selected document indices: %v\n", supportedIndices)

	supportedResults := make([]RetrievalResult, 0)
	for _, idx := range supportedIndices {
		if idx >= 0 && idx < len(retrievedResults) {
			supportedResults = append(supportedResults, retrievedResults[idx])
		}
	}

	fmt.Printf("[ChainOfRAG]   Filtered to %d supported documents\n", len(supportedResults))
	fmt.Printf("[ChainOfRAG]   Tokens used: %d\n", response.TotalTokens)
	return supportedResults, response.TotalTokens, nil
}

// checkHasEnoughInfo checks if there's enough information to answer the query
func (c *ChainOfRAG) checkHasEnoughInfo(ctx context.Context, query string, intermediateContexts []string) (bool, int, error) {
	fmt.Printf("[ChainOfRAG] Step 4: Checking if enough information gathered...\n")
	fmt.Printf("[ChainOfRAG]   Intermediate contexts: %d\n", len(intermediateContexts))

	if len(intermediateContexts) == 0 {
		fmt.Printf("[ChainOfRAG]   No intermediate contexts, need more information\n")
		return false, 0, nil
	}

	contextStr := strings.Join(intermediateContexts, "\n")
	prompt := fmt.Sprintf(reflectionPrompt, contextStr, query)

	response, err := c.llm.Chat(ctx, []llm.ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		fmt.Printf("[ChainOfRAG]   ERROR: Failed to check information: %v\n", err)
		return false, 0, err
	}

	content := strings.ToLower(strings.TrimSpace(response.Content))
	hasEnoughInfo := content == "yes"
	fmt.Printf("[ChainOfRAG]   Reflection result: %s (hasEnoughInfo: %v)\n", response.Content, hasEnoughInfo)
	fmt.Printf("[ChainOfRAG]   Tokens used: %d\n", response.TotalTokens)
	return hasEnoughInfo, response.TotalTokens, nil
}

// Invoke executes the agent with the given query and returns the result.
// This implements the BaseAgent interface.
// For ChainOfRAG, Invoke calls Query and returns the answer string.
func (c *ChainOfRAG) Invoke(ctx context.Context, query string, kwargs map[string]interface{}) (interface{}, error) {
	answer, _, _, err := c.Query(ctx, query, kwargs)
	if err != nil {
		return nil, err
	}
	return answer, nil
}

// Retrieve retrieves relevant documents based on the input query and iteratively refines the search
// This implements the RAGAgent interface
func (c *ChainOfRAG) Retrieve(ctx context.Context, query string, kwargs map[string]interface{}) ([]RetrievalResult, int, map[string]interface{}, error) {
	topK := c.config.TopK
	threshold := c.config.Threshold

	if kwargs != nil {
		if topKVal, ok := kwargs["top_k"].(int); ok {
			topK = topKVal
		}
		if thresholdVal, ok := kwargs["threshold"].(float64); ok {
			threshold = thresholdVal
		}
	}

	iterations := c.maxIter
	if kwargs != nil {
		if maxIterVal, ok := kwargs["max_iter"].(int); ok {
			iterations = maxIterVal
		}
	}

	fmt.Printf("[ChainOfRAG] ===== Starting Retrieve Phase =====\n")
	fmt.Printf("[ChainOfRAG] Original query: %s\n", query)
	fmt.Printf("[ChainOfRAG] Max iterations: %d, Early stopping: %v\n", iterations, c.earlyStopping)
	fmt.Printf("[ChainOfRAG] TopK: %d, Threshold: %.2f\n", topK, threshold)

	intermediateContexts := make([]string, 0)
	allRetrievedResults := make([]RetrievalResult, 0)
	tokenUsage := 0

	fallback := false

	for iter := 0; iter < iterations; iter++ {
		fmt.Printf("\n[ChainOfRAG] --- Iteration %d/%d ---\n", iter+1, iterations)

		followupQuery, nToken0, err := c.reflectGetSubquery(ctx, query, intermediateContexts)
		if err != nil {
			fallback = true
			fmt.Printf("[ChainOfRAG]   ERROR: Failed to generate follow-up query: %v\n", err)
			break
		}

		intermediateAnswer, retrievedResults, nToken1, err := c.retrieveAndAnswer(ctx, followupQuery, topK, threshold)
		if err != nil {
			fallback = true
			fmt.Printf("[ChainOfRAG]   ERROR: Failed to retrieve and answer: %v\n", err)
			break
		}

		supportedRetrievedResults, nToken2, err := c.getSupportedDocs(ctx, retrievedResults, followupQuery, intermediateAnswer)
		if err != nil {
			fallback = true
			fmt.Printf("[ChainOfRAG]   ERROR: Failed to filter supported documents: %v\n", err)
			break
		}

		allRetrievedResults = append(allRetrievedResults, supportedRetrievedResults...)
		intermediateIdx := len(intermediateContexts) + 1
		intermediateContexts = append(intermediateContexts,
			fmt.Sprintf("Intermediate query%d: %s\nIntermediate answer%d: %s", intermediateIdx, followupQuery, intermediateIdx, intermediateAnswer))
		tokenUsage += nToken0 + nToken1 + nToken2

		fmt.Printf("[ChainOfRAG]   Accumulated documents: %d\n", len(allRetrievedResults))
		fmt.Printf("[ChainOfRAG]   Accumulated intermediate contexts: %d\n", len(intermediateContexts))
		fmt.Printf("[ChainOfRAG]   Total tokens used so far: %d\n", tokenUsage)

		if c.earlyStopping {
			hasEnoughInfo, nTokenCheck, err := c.checkHasEnoughInfo(ctx, query, intermediateContexts)
			if err != nil {
				fallback = true
				fmt.Printf("[ChainOfRAG]   ERROR: Failed to check if enough information gathered: %v\n", err)
				break
			}
			tokenUsage += nTokenCheck

			if hasEnoughInfo {
				fmt.Printf("[ChainOfRAG]   ✓ Early stopping: Enough information gathered\n")
				break
			}
		}
	}

	fmt.Printf("\n[ChainOfRAG] --- Final Processing ---\n")
	allRetrievedResults = deduplicateResults(allRetrievedResults)
	fmt.Printf("[ChainOfRAG] Final deduplicated documents: %d\n", len(allRetrievedResults))
	fmt.Printf("[ChainOfRAG] Total iterations completed: %d\n", len(intermediateContexts))
	fmt.Printf("[ChainOfRAG] Total tokens used: %d\n", tokenUsage)

	// Fallback: If no results found through iterative retrieval, use main query directly
	if len(allRetrievedResults) == 0 || fallback == true {
		fmt.Printf("[ChainOfRAG] --- Fallback: No results found (or content moderation error), querying with main query ---\n")
		fmt.Printf("[ChainOfRAG] Fallback query: %s\n", query)

		// Get embedding for the main query
		queryVector, err := c.embeddingModel.GetEmbedding(ctx, query)
		if err != nil {
			fmt.Printf("[ChainOfRAG] Fallback ERROR: Failed to get embedding: %v\n", err)
			// Continue with empty results rather than failing
		} else {
			// Search directly with main query
			searchOptions := &schema.SearchOptions{
				TopK:      topK,
				Threshold: threshold,
			}
			searchResults := make([]schema.SearchResult, 0)
			if c.config.HybridSearch {
				searchResults, err = c.vectorDB.SearchHybridDocs(ctx, query, queryVector, searchOptions)
			} else {
				searchResults, err = c.vectorDB.SearchDocs(ctx, query, queryVector, searchOptions)
			}

			if err != nil {
				fmt.Printf("[ChainOfRAG] Fallback ERROR: Search failed: %v\n", err)
			} else {
				fmt.Printf("[ChainOfRAG] Fallback retrieved %d documents\n", len(searchResults))

				// Convert search results to RetrievalResult
				fallbackResults := make([]RetrievalResult, 0, len(searchResults))
				for _, result := range searchResults {
					fallbackResults = append(fallbackResults, RetrievalResult{
						Text:     result.Document.Content,
						Score:    result.Score,
						Document: result.Document,
						Metadata: result.Document.Metadata,
					})
				}

				allRetrievedResults = deduplicateResults(fallbackResults)
				fmt.Printf("[ChainOfRAG] Fallback final documents: %d\n", len(allRetrievedResults))
			}
		}
	}

	fmt.Printf("[ChainOfRAG] ===== Retrieve Phase Completed =====\n\n")

	additionalInfo := map[string]interface{}{
		"intermediate_context": intermediateContexts,
		"used_fallback":        len(intermediateContexts) == 0 && len(allRetrievedResults) > 0,
	}

	if len(allRetrievedResults) > topK {
		allRetrievedResults = allRetrievedResults[:topK]
	}

	fmt.Printf("[ChainOfRAG]   Final retrieved documents: %d\n", len(allRetrievedResults))

	return allRetrievedResults, tokenUsage, additionalInfo, nil
}

// Query executes a query and returns the final answer along with all retrieved results
// This implements the RAGAgent interface
func (c *ChainOfRAG) Query(ctx context.Context, query string, kwargs map[string]interface{}) (string, []RetrievalResult, int, error) {
	fmt.Printf("[ChainOfRAG] ===== Starting Query Phase =====\n")
	fmt.Printf("[ChainOfRAG] Query: %s\n", query)

	allRetrievedResults, nTokenRetrieval, additionalInfo, err := c.Retrieve(ctx, query, kwargs)
	if err != nil {
		fmt.Printf("[ChainOfRAG] ERROR: Retrieve failed: %v\n", err)
		return "", nil, 0, err
	}

	fmt.Printf("[ChainOfRAG] Step 5: Generating final answer...\n")
	fmt.Printf("[ChainOfRAG]   Retrieved documents: %d\n", len(allRetrievedResults))
	fmt.Printf("[ChainOfRAG]   Retrieval tokens used: %d\n", nTokenRetrieval)

	intermediateContext, ok := additionalInfo["intermediate_context"].([]string)
	if !ok {
		intermediateContext = []string{}
	}
	fmt.Printf("[ChainOfRAG]   Intermediate contexts: %d\n", len(intermediateContext))

	formattedDocs := c.formatRetrievedResults(allRetrievedResults)
	contextStr := strings.Join(intermediateContext, "\n")
	prompt := fmt.Sprintf(finalAnswerPrompt, formattedDocs, contextStr, query)

	response, err := c.llm.Chat(ctx, []llm.ChatMessage{
		{Role: "user", Content: prompt},
	})
	if err != nil {
		fmt.Printf("[ChainOfRAG] ERROR: Failed to generate final answer: %v\n", err)
		return "", nil, 0, err
	}

	finalAnswer := response.Content
	totalTokens := nTokenRetrieval + response.TotalTokens
	fmt.Printf("[ChainOfRAG]   Final answer generated (length: %d chars)\n", len(finalAnswer))
	fmt.Printf("[ChainOfRAG]   Final answer tokens: %d\n", response.TotalTokens)
	fmt.Printf("[ChainOfRAG]   Total tokens (retrieval + generation): %d\n", totalTokens)
	fmt.Printf("[ChainOfRAG] ===== Query Phase Completed =====\n\n")

	return finalAnswer, allRetrievedResults, totalTokens, nil
}

// formatRetrievedResults formats retrieved results for prompt
func (c *ChainOfRAG) formatRetrievedResults(retrievedResults []RetrievalResult) string {
	formattedDocuments := make([]string, 0)
	for i, result := range retrievedResults {
		text := result.Text
		formattedDocuments = append(formattedDocuments, fmt.Sprintf("<Document %d>\n%s\n</Document %d>", i, text, i))
	}
	return strings.Join(formattedDocuments, "\n")
}

// deduplicateResults removes duplicate results based on text content
func deduplicateResults(results []RetrievalResult) []RetrievalResult {
	seen := make(map[string]bool)
	deduplicated := make([]RetrievalResult, 0)

	for _, result := range results {
		if !seen[result.Text] {
			seen[result.Text] = true
			deduplicated = append(deduplicated, result)
		}
	}

	return deduplicated
}

// LiteralEval parses a string response into a list of integers
func LiteralEval(content string) ([]int, error) {
	content = strings.TrimSpace(content)
	// Note: RemoveThink is already called in llm.Provider.Chat, but we call it again here
	// in case this function is called with content that didn't go through Chat
	content = llm.RemoveThink(content)

	// Remove code blocks if present
	if strings.HasPrefix(content, "```") {
		lines := strings.Split(content, "\n")
		if len(lines) > 1 {
			content = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}

	// Try to find list pattern
	re := regexp.MustCompile(`\[[\d\s,]+\]`)
	matches := re.FindString(content)
	if matches == "" {
		// Try to find any list-like structure
		re2 := regexp.MustCompile(`\[.*?\]`)
		matches = re2.FindString(content)
	}

	if matches == "" {
		return nil, fmt.Errorf("no list found in content: %s", content)
	}

	// Parse the list
	matches = strings.Trim(matches, "[]")
	parts := strings.Split(matches, ",")
	result := make([]int, 0)

	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		val, err := strconv.Atoi(part)
		if err != nil {
			return nil, fmt.Errorf("invalid integer in list: %s", part)
		}
		result = append(result, val)
	}

	return result, nil
}
